name: Python application

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # v2에서 v3로 업데이트
    - name: Set up Python 3.8
      uses: actions/setup-python@v4  # v2에서 v4로 업데이트
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script
      run: python new.py  # 여기서 파일 경로를 확인하세요
