name: Python application

on:
  schedule:
    - cron: '10 0 * * *'  # 매일 UTC 00:10에 실행 (한국 시간 오전 9:10)
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script
      run: python newtest.py
